# Generated by Django 2.0 on 2017-12-26 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('country_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CountryUserPref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Country')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('discipline_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineUserPref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Discipline')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntranceExam',
            fields=[
                ('entrance_exam_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('instt_code', models.AutoField(primary_key=True, serialize=False)),
                ('instt_name', models.CharField(max_length=200)),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(blank=True, max_length=200, null=True)),
                ('address_3', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pin_code', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Country')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteCutOffs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4)),
                ('quota', models.CharField(blank=True, max_length=10)),
                ('cutOff', models.IntegerField(blank=True)),
                ('Discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Discipline')),
                ('Institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteJEERanks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4)),
                ('quota', models.CharField(blank=True, max_length=10)),
                ('opening_rank', models.IntegerField(blank=True)),
                ('closing_rank', models.IntegerField(blank=True)),
                ('Discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Discipline')),
                ('Institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteProgramEntrance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Discipline')),
                ('EntranceExam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NextSteps.EntranceExam')),
                ('Institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutePrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_duration', models.CharField(blank=True, max_length=30)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Country')),
                ('Discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Discipline')),
                ('Institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NextSteps.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteProgramSeats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_seats', models.IntegerField(blank=True)),
                ('Discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Discipline')),
                ('Institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteSurveyRanking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4)),
                ('rank', models.IntegerField(blank=True, default=0)),
                ('Discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Discipline')),
                ('Institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NextSteps.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteType',
            fields=[
                ('instt_type_cd', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InsttUserPref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Country')),
                ('Discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Discipline')),
                ('Institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('level_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LevelUserPref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Level')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramUserPref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Program')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeatQuota',
            fields=[
                ('seat_quota_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('survey_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('parameter', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=10)),
                ('Survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Survey')),
            ],
        ),
        migrations.AddField(
            model_name='insttuserpref',
            name='Level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Level'),
        ),
        migrations.AddField(
            model_name='insttuserpref',
            name='Program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Program'),
        ),
        migrations.AddField(
            model_name='insttuserpref',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutesurveyranking',
            name='Survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Survey'),
        ),
        migrations.AddField(
            model_name='instituteprogramseats',
            name='Level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Level'),
        ),
        migrations.AddField(
            model_name='instituteprogramseats',
            name='Program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Program'),
        ),
        migrations.AddField(
            model_name='instituteprogramseats',
            name='SeatQuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NextSteps.SeatQuota'),
        ),
        migrations.AddField(
            model_name='instituteprograms',
            name='Level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Level'),
        ),
        migrations.AddField(
            model_name='instituteprograms',
            name='Program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Program'),
        ),
        migrations.AddField(
            model_name='instituteprogramentrance',
            name='Level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Level'),
        ),
        migrations.AddField(
            model_name='instituteprogramentrance',
            name='Program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Program'),
        ),
        migrations.AddField(
            model_name='institutejeeranks',
            name='Level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Level'),
        ),
        migrations.AddField(
            model_name='institutejeeranks',
            name='Program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Program'),
        ),
        migrations.AddField(
            model_name='institutecutoffs',
            name='Level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Level'),
        ),
        migrations.AddField(
            model_name='institutecutoffs',
            name='Program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Program'),
        ),
        migrations.AddField(
            model_name='institute',
            name='InstituteType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NextSteps.InstituteType'),
        ),
    ]
