# Generated by Django 2.0 on 2017-12-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0002_auto_20171227_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='discipline_code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entranceexam',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entranceexam',
            name='entrance_exam_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='institute',
            name='address_1',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='institute',
            name='address_2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='address_3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='institute',
            name='instt_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='institute',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seatquota',
            name='seat_quota_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='surveyparameters',
            name='parameter',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='surveyparameters',
            name='score',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
