# Generated by Django 2.0 on 2018-01-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0003_auto_20171231_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='degree',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_code',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
