# Generated by Django 2.0 on 2018-01-03 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0004_auto_20180102_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insttuserpref',
            name='Level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Level'),
        ),
    ]
