# Generated by Django 2.0 on 2018-01-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0006_auto_20180103_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='instt_name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='institutecutoffs',
            name='cutOff',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
