# Generated by Django 2.0 on 2018-01-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0008_instituteprogramimpdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please use your login name in case you are registered user.', max_length=200)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', help_text="Please don't forget the STD code in case using landline.", max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=4000)),
                ('msg_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('response', models.CharField(blank=True, default='', editable=False, max_length=1000)),
                ('resp_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('reponded_by', models.CharField(blank=True, default='', editable=False, max_length=30)),
            ],
        ),
    ]
