# Generated by Django 2.0 on 2018-01-06 16:55

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0010_auto_20180106_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='msg_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(max_length=200, validators=[django.contrib.auth.validators.ASCIIUsernameValidator]),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='resp_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
