# Generated by Django 2.0 on 2018-01-21 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0015_auto_20180116_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteprogramentrance',
            name='Country',
            field=models.ForeignKey(default='India', on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instituteprogramimpdates',
            name='Country',
            field=models.ForeignKey(default='India', on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instituteprogramseats',
            name='Country',
            field=models.ForeignKey(default='India', on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institutesurveyranking',
            name='Country',
            field=models.ForeignKey(default='India', on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='Country',
            field=models.ForeignKey(default='India', on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyparameters',
            name='Discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NextSteps.Discipline'),
        ),
        migrations.AddField(
            model_name='surveyparameters',
            name='Level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NextSteps.Level'),
        ),
    ]
