# Generated by Django 2.0 on 2018-01-29 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0016_auto_20180121_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instituteadmroutes',
            old_name='Description',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='institute',
            name='email_id',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='insttuserpref',
            name='Program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Program'),
        ),
    ]
