# Generated by Django 2.0 on 2018-02-05 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NextSteps', '0017_auto_20180129_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=10)),
                ('mothers_name', models.CharField(blank=True, default='', max_length=200)),
                ('mothers_qualification', models.CharField(blank=True, default='', max_length=200)),
                ('mothers_occupation', models.CharField(blank=True, default='', max_length=200)),
                ('mothers_income', models.CharField(blank=True, default='', max_length=200)),
                ('fathers_name', models.CharField(blank=True, default='', max_length=200)),
                ('fathers_qualification', models.CharField(blank=True, default='', max_length=200)),
                ('fathers_occupation', models.CharField(blank=True, default='', max_length=200)),
                ('fathers_income', models.CharField(blank=True, default='', max_length=200)),
                ('person_with_disability', models.NullBooleanField(default=False)),
                ('percetage_of_diability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('state_of_eligibility', models.CharField(blank=True, default='', max_length=200)),
                ('nationality', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('locality', models.CharField(blank=True, default='', max_length=300)),
                ('city_town_village', models.CharField(blank=True, default='', max_length=300)),
                ('district', models.CharField(blank=True, default='', max_length=300)),
                ('pin_code', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('email_id', models.EmailField(blank=True, default='', max_length=254)),
                ('adhaar_number', models.IntegerField(blank=True, null=True)),
                ('class_10th_year_of_passing', models.CharField(blank=True, default='', max_length=4)),
                ('class_10th_percentage_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('class_10th_school_address', models.TextField(blank=True, default='', max_length=3000)),
                ('class_10th_board_or_university', models.CharField(blank=True, default='', max_length=300)),
                ('class_12th_year_of_passing', models.CharField(blank=True, default='', max_length=4)),
                ('class_12th_percentage_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('class_12th_school_address', models.TextField(blank=True, default='', max_length=3000)),
                ('class_12th_board_or_university', models.CharField(blank=True, default='', max_length=300)),
                ('guardians_name', models.CharField(blank=True, default='', max_length=300)),
                ('guardians_qualification', models.CharField(blank=True, default='', max_length=200)),
                ('guardians_occupation', models.CharField(blank=True, default='', max_length=200)),
                ('guardians_income', models.CharField(blank=True, default='', max_length=200)),
                ('candidate_photo', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('candidate_signature', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('parent_signature', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Country')),
                ('StudentCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='NextSteps.StudentCategory')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='institutetype',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
