# Generated by Django 2.0 on 2018-02-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0019_auto_20180206_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituteprogramimpdates',
            name='date',
        ),
        migrations.AddField(
            model_name='institute',
            name='abbreviation',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='institute',
            name='aicte_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='instituteprogramimpdates',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instituteprogramimpdates',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instituteprogramimpdates',
            name='event_duration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instituteprogramimpdates',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='instituteprogramimpdates',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userappdetails',
            name='candidate_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='userappdetails',
            name='candidate_signature',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='userappdetails',
            name='parent_signature',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='userappdetails',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
