# Generated by Django 2.0 on 2018-03-08 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0020_auto_20180219_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='JEEMAINdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('event', models.CharField(blank=True, default='', max_length=500)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_order', models.IntegerField(blank=True, null=True)),
                ('event_duration_days', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='response',
            field=models.CharField(blank=True, default='', editable=False, max_length=4000),
        ),
        migrations.AlterField(
            model_name='entranceexam',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='instt_name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='institutetype',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_code',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='promotion_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seatquota',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userappdetails',
            name='Country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Country'),
        ),
    ]
