# Generated by Django 2.0 on 2018-03-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0022_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='userappdetails',
            name='address',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
