# Generated by Django 2.0 on 2018-03-28 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NextSteps', '0023_auto_20180316_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCalendar',
            fields=[
                ('id', models.DecimalField(decimal_places=25, max_digits=30, primary_key=True, serialize=False)),
                ('event', models.CharField(blank=True, default='', max_length=500)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_order', models.IntegerField(blank=True, null=True)),
                ('event_duration_days', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=2000)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Country')),
                ('Discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Discipline')),
                ('Institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Institute')),
                ('Level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Level')),
                ('Program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Program')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
