# Generated by Django 2.0 on 2018-03-28 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0024_usercalendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercalendar',
            name='Country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Country'),
        ),
        migrations.AlterField(
            model_name='usercalendar',
            name='Discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Discipline'),
        ),
        migrations.AlterField(
            model_name='usercalendar',
            name='Institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Institute'),
        ),
        migrations.AlterField(
            model_name='usercalendar',
            name='Level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Level'),
        ),
        migrations.AlterField(
            model_name='usercalendar',
            name='Program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Program'),
        ),
    ]
