# Generated by Django 2.0 on 2018-03-29 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0025_auto_20180328_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercalendar',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
