# Generated by Django 2.0 on 2018-04-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0028_auto_20180410_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='entranceexam',
            name='exam_level',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='entranceexam',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
