# Generated by Django 2.0 on 2018-04-12 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0030_entranceexam_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituteadmroutes',
            name='Program',
        ),
    ]
