# Generated by Django 2.0 on 2018-04-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0032_auto_20180412_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='jee_flag',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
