# Generated by Django 2.0 on 2018-07-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0033_institute_jee_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_group',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
