# Generated by Django 2.0 on 2018-08-09 06:07

import NextSteps.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0035_studyhours_subjects_userstudyschedule_usersubjectschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyhours',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyhours',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubjectschedule',
            name='percentage_weight',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, validators=[NextSteps.validators.validate_max100], verbose_name='Allocation(%)'),
        ),
    ]
