# Generated by Django 2.0 on 2018-08-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0036_auto_20180809_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyhours',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
