# Generated by Django 2.0 on 2018-08-10 08:00

import NextSteps.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NextSteps', '0037_auto_20180809_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDaySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=2000)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('planned_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[NextSteps.validators.validate_max24hrs])),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
