# Generated by Django 2.0 on 2018-08-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0038_userdayschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyhours',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyhours',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
