# Generated by Django 2.0.3 on 2018-09-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0039_auto_20180811_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdayschedule',
            name='date_udpated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstudyschedule',
            name='date_udpated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubjectschedule',
            name='date_udpated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
