# Generated by Django 2.0.3 on 2018-09-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0040_auto_20180905_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstudyschedule',
            old_name='date_udpated',
            new_name='date_updated',
        ),
    ]
