# Generated by Django 2.0.3 on 2018-09-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0041_auto_20180905_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdayschedule',
            old_name='date_udpated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='usersubjectschedule',
            old_name='date_udpated',
            new_name='date_updated',
        ),
    ]
