# Generated by Django 2.0.3 on 2018-09-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0042_auto_20180905_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdayschedule',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstudyschedule',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubjectschedule',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
