# Generated by Django 2.0.3 on 2018-09-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0045_auto_20180921_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='payment_address1',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='payment_address2',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='payment_city',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='payment_country',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='payment_email',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='payment_firstname',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='payment_lastname',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='payment_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='payment_state',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='payment_zip_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
