# Generated by Django 2.0.3 on 2018-09-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0047_auto_20180926_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubjectschedule',
            name='fri',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='usersubjectschedule',
            name='mon',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='usersubjectschedule',
            name='sat',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='usersubjectschedule',
            name='sun',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='usersubjectschedule',
            name='thu',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='usersubjectschedule',
            name='tue',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='usersubjectschedule',
            name='wed',
            field=models.NullBooleanField(),
        ),
    ]
