# Generated by Django 2.0.3 on 2018-09-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0048_auto_20180926_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubjectschedule',
            name='fri',
        ),
        migrations.RemoveField(
            model_name='usersubjectschedule',
            name='mon',
        ),
        migrations.RemoveField(
            model_name='usersubjectschedule',
            name='sat',
        ),
        migrations.RemoveField(
            model_name='usersubjectschedule',
            name='sun',
        ),
        migrations.RemoveField(
            model_name='usersubjectschedule',
            name='thu',
        ),
        migrations.RemoveField(
            model_name='usersubjectschedule',
            name='tue',
        ),
        migrations.RemoveField(
            model_name='usersubjectschedule',
            name='wed',
        ),
        migrations.AddField(
            model_name='userdayschedule',
            name='fri',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='userdayschedule',
            name='mon',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='userdayschedule',
            name='sat',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='userdayschedule',
            name='sun',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='userdayschedule',
            name='thu',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='userdayschedule',
            name='tue',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='userdayschedule',
            name='wed',
            field=models.NullBooleanField(),
        ),
    ]
