# Generated by Django 2.0.3 on 2018-09-27 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0049_auto_20180927_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappdetails',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
