# Generated by Django 2.0.3 on 2018-09-27 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0050_auto_20180927_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userappdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='userappdetails',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
