# Generated by Django 2.0.3 on 2018-09-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0052_beforepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beforepayment',
            name='PromotionCode',
        ),
        migrations.AddField(
            model_name='beforepayment',
            name='promotionCode',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='beforepayment',
            name='discount_percent',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='promotion_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
