# Generated by Django 2.0.3 on 2018-09-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0053_auto_20180928_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beforepayment',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
