# Generated by Django 2.0.3 on 2018-12-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0054_auto_20180928_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutesurveyranking',
            name='rank',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
