# Generated by Django 2.0.3 on 2018-12-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0055_auto_20181203_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcategory',
            name='jee_flag',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
