# Generated by Django 2.0.3 on 2018-12-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0056_studentcategory_jee_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutecutoffs',
            name='quota',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='institutejeeranks',
            name='quota',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='instituteprogramseats',
            name='quota',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='seatquota',
            name='seat_quota_code',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
