# Generated by Django 2.0.3 on 2018-12-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0057_auto_20181205_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncode',
            name='display_in_homepage',
            field=models.NullBooleanField(default=False),
        ),
    ]
