# Generated by Django 2.0.3 on 2018-12-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0058_promotioncode_display_in_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcategory',
            name='used_by_nta',
            field=models.NullBooleanField(default=False),
        ),
    ]
