# Generated by Django 2.0.3 on 2018-12-24 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0059_studentcategory_used_by_nta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcategory',
            name='used_by_nta',
        ),
    ]
