# Generated by Django 2.1.4 on 2019-01-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextSteps', '0060_remove_studentcategory_used_by_nta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beforepayment',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
