# Generated by Django 2.1.4 on 2019-01-09 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NextSteps', '0061_auto_20190104_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=600)),
                ('address_1', models.CharField(blank=True, default='', max_length=600)),
                ('address_2', models.CharField(blank=True, default='', max_length=600)),
                ('city', models.CharField(blank=True, default='', max_length=300)),
                ('pin_code', models.PositiveIntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('email_id', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_person', models.CharField(blank=True, default='', max_length=2000)),
                ('Country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='NextSteps.Country')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partner_promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NextSteps.Partner')),
                ('PromotionCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NextSteps.PromotionCode')),
            ],
        ),
    ]
